### ISSUE TITLE
Missing CHANGES, dataset_description.json, participants.tsv.

### ISSUE THREAD

**Issue by njhunsak** [jolynnjones/psych516w2020#1]
1. Your BIDS directory looks nearly perfect. You need to include in the directory:  CHANGES, dataset_description.json, participants.tsv files
https://github.com/jolynnjones/psych516w2020/blob/312ea1b2b172e526ef47b45862a741c6ea2bece8/EDSD-tree.txt#L1
2. On a few participants, you have an extra image that needs to be removed.
https://github.com/jolynnjones/psych516w2020/blob/312ea1b2b172e526ef47b45862a741c6ea2bece8/EDSD-tree.txt#L6-L7
3. We don't have any functional data so you don't need a functional subdirectory.
https://github.com/jolynnjones/psych516w2020/blob/312ea1b2b172e526ef47b45862a741c6ea2bece8/EDSD-tree.txt#L13

**Comment by njhunsak** [comment]
Have you been able to generate a least one ACPC aligned image from freeview? Please upload at least one image.

**Comment by jolynnjones** [comment]
Yes I have. I just haven’t had a chance to upload it yet.

**Comment by jolynnjones** [comment]
I just uploaded my code for acpcdetect as well as the images. Somehow, I deleted the file for sub-FREAD001, so that one is not currently listed in the png folder.

**Comment by njhunsak** [comment]
Looks great!
