### ISSUE TITLE
Freesurfer recon-all

### ISSUE THREAD

**Issue by njhunsak** [jolynnjones/psych516w2020#2]
1. You only ran one participant and not all participants?

https://github.com/jolynnjones/psych516w2020/blob/fb780673d3207ef58c7a478b69fd38cff1568f6a/recon-all_batch.sh#L6

https://github.com/jolynnjones/psych516w2020/blob/fb780673d3207ef58c7a478b69fd38cff1568f6a/recon-all_bigv_batch.sh#L6

2. This label is confusing since you are running freesurfer reconall and not T1 preprocessing

https://github.com/jolynnjones/psych516w2020/blob/fb780673d3207ef58c7a478b69fd38cff1568f6a/recon-all_batch.sh#L4

https://github.com/jolynnjones/psych516w2020/blob/fb780673d3207ef58c7a478b69fd38cff1568f6a/recon-all_bigv_batch.sh#L4

3. You do not include subject ID when listing the directory where ALL freesurfer subjects are located.

https://github.com/jolynnjones/psych516w2020/blob/fb780673d3207ef58c7a478b69fd38cff1568f6a/recon-all_job.sh#L20

https://github.com/jolynnjones/psych516w2020/blob/fb780673d3207ef58c7a478b69fd38cff1568f6a/recon-all_bigv_job.sh#L21

**Comment by njhunsak** [comment]
Everything looks great except for the last issue (#3). Please remove subject ID from the `-sd` command in your recon-all code. The `-sd` is the location for ALL participants and isn't meant to include your specific subject ID.

**Comment by jolynnjones** [comment]
I made those changes.
