### ISSUE TITLE
Output to CSV

### ISSUE THREAD

**Issue by njhunsak** [jolynnjones/psych516w2020#3]
The challenge with this assignment was figuring out how to output this to a CSV file. The script looks fine, but you aren't generating a CSV file with subjectID, total volumes in NIFTI, bval count, bvec count.

https://github.com/jolynnjones/psych516w2020/blob/a6e17f044bb2af78d791b9055f4e02055b8e89d3/Week_6/dwi_verify.sh#L1-L11

**Comment by jolynnjones** [comment]
I got it figured out:)
